### ISSUE TITLE
Teams klinks als een verzameling, is team niet een betere naam?

### ISSUE THREAD

**Issue by gaico** [JansenME/competition#1]
https://github.com/JansenME/competition/blob/815bc774f3914c899b7d7ea7b4e0b225ff3d311a/src/main/java/com/competition/model/Teams.java#L9

**Comment by JansenME** [comment]
Done.

Matches moet wel blijven als meervoud helaas. Match is een keyword in MySQL dus als de class Match heet, maakt Hibernate een verkeerde query aan.
